### ISSUE TITLE
Pytorch 2.x?

### ISSUE THREAD

**Issue by ankile** [hengyuan-hu/monometis#4]
Hey, Hengyuan!

I've had similar issues with Polymetis not being actively maintained anymore so I appreciate this effort. Does this version of Polymetis/Monometis support PyTorch 2 and above as well? Also, is this currently the framework for Franka control you've found the easiest to work with or have you moved on?

Best, Lars

**Comment by hengyuan-hu** [comment]
This works with pytorch 2.0 but I am not sure if it works with the newest. We now just run it on the NUC side and communicates actions through our own interface so we never need to upgrade it again. This is the only one that I have used because the rest of the lab uses polymetis. I would not suggest this if you do not have to use it for some legacy reason. Polymetis is bad software in (every) aspect.
